### ISSUE TITLE
TypeError: labels.columnNames[lang] is undefined

### ISSUE THREAD

**Issue by iandevlin** [SergioCrisostomo/js-calendar#1]
Hello!
I have tried to use the addLabels iterator function as specified in the documentation, but it keeps returning the above error on line 22 of addLabels.js.

I will have a look myself and issue a merge request should I solve it, but thought I would post it here too as an issue in case you were bored and wanted something to do :D

**Comment by SergioCrisostomo** [comment]
Fixed in https://github.com/SergioCrisostomo/js-calendar/issues/1
