### ISSUE TITLE
How to handle extra weeks in calendar that don't belong to current month?

### ISSUE THREAD

**Issue by SergioCrisostomo** [SergioCrisostomo/js-calendar#12]
Some months need 6 rows (May example), some months need only 4 (February example). How to handle this difference? 

jsFiddle: http://jsfiddle.net/La7cwne8/3/

Possible behaviours:
- a) not produce those cells
- b) procude them, with a special type (distinguishing them from `prevMonth` and `nextMonth` types)
- c) produce them and leave it as it is with `nextMonth` type

![image](https://cloud.githubusercontent.com/assets/5614559/11936072/e28cd5c0-a80b-11e5-82d1-af8bc62addd3.png)

My own vote is either c) or b).

**Comment by iandevlin** [comment]
How about:
d) add a boolean "hidden" flag which indicates whether a day is actually hidden in this case.
I think the week might need it too though (if all days in the week are hidden) so one can decide to not display that week if required.

**Comment by SergioCrisostomo** [comment]
@iandevlin and in that d) option should the hidden days before the month start also have that flag? or only the ones after the month ended?

There could be a `e)` option. To pass it in the configuration object together with `weekStart` and `onlyDays`

**Comment by iandevlin** [comment]
@SergioCrisostomo I think all days should have it, as the visible days would have it set to false.
And yes, a config option is possibly a better idea.
