### ISSUE TITLE
Week number is incorrect on year turnover

### ISSUE THREAD

**Issue by iandevlin** [SergioCrisostomo/js-calendar#3]
The information returned for the 2016-01 returns incorrect week numbers as the code does not take the change into account.
The first week of January is week 53 (from the previous year) and then needs to restart from 1 but it does not, it just continues incrementing the week number.

Again I am looking at fixing this, but if you know the code better than I do.

**Comment by iandevlin** [comment]
Fixed with #4.

**Comment by SergioCrisostomo** [comment]
@iandevlin thank you for reporting this!

I made [a new spec that covers this](https://github.com/SergioCrisostomo/js-calendar/commit/a478c3bbc0011e67a954b22f7b3f544fa547a197) and fixed the problem in the code.
