### ISSUE TITLE
Incorrect Week Number for Last Week of 2014

### ISSUE THREAD

**Issue by iandevlin** [SergioCrisostomo/js-calendar#5]
I have found another small issue with relation to week numbers.
When getting data for January 2015, the first week number is 1, even though this includes some dates from December. This is correct.
But when you then get data for December 2014, the last week number is 53, even though it should actually be 1 (2015) as 2014 only has 52 weeks.

(Week data retrieved from http://www.epochconverter.com/date-and-time/weeknumbers-by-year.php?year=2014)

**Comment by SergioCrisostomo** [comment]
Good point. Nice to get those working correct. If you want you can make a spec for it and I can look at a fix for it later today. ( i can also add a spec if you don't have time)

**Comment by iandevlin** [comment]
I am not sure how these are worked out to be honest! The main reason I looked for someone's library is because this stuff is such a pain in the butt :-)
I appreciate your work, and your very quick replies!

**Comment by iandevlin** [comment]
I found https://gist.github.com/dblock/1081513 which seems to get the correct week number for a Date().

e.g.

```javascript
Date.prototype.getWeek = function() {
    // Create a copy of this date object
    var target  = new Date(this.valueOf());
    // ISO week date weeks start on monday
    // so correct the day number
    var dayNr   = (this.getDay() + 6) % 7;
    // Set the target to the thursday of this week so the
    // target date is in the right year
    target.setDate(target.getDate() - dayNr + 3);
    // ISO 8601 states that week 1 is the week
    // with january 4th in it
    var jan4    = new Date(target.getFullYear(), 0, 4);
    // Number of days between target date and january 4th
    var dayDiff = (target - jan4) / 86400000;
    // Calculate week number: Week 1 (january 4th) plus the
    // number of weeks between target date and january 4th
    var weekNr = 1 + Math.ceil(dayDiff / 7);
    return weekNr;
}
```

So it might be worth working with something like this.

**Comment by iandevlin** [comment]
Thanks, although this doesn't appear to fix things correctly, as although the week number is correct, the year is now incorrect.

e.g. the last week in December should be 2015 week 1, whereas it is being set to 2014 week 1, and the first week in January 2015 has the same issue.

Sorry to be such a pain in pointing these out.

**Comment by SergioCrisostomo** [comment]
@iandevlin I am happy you point things out. I fixed it late night so I might have missed something.
I didn't change the `year` logic though, but I will look why date is being wrong set.

**Comment by SergioCrisostomo** [comment]
@iandevlin I cannot find the problem you pointed out. Can you look at this jsFiddle and reproduce the error? -> http://jsfiddle.net/xts0rL1k/

**Comment by iandevlin** [comment]
The problem is that the only way to get the year from the date, is by extracting it from the datetime variable, which then gives you the wrong year for the week, but it is the correct one for the date.

e.g. in your jsFiddle, for the jan2014 data, the week number is correct but the extracted year would be incorrect, i.e. 2013 and not 2014.
The same applies to the jan2015 data.

I am just wondering if there needs to be an extra field that holds the week year, even though most of the time it is the same as the year contained within the datetime value.

Or am I reading things wrong?

**Comment by SergioCrisostomo** [comment]
@iandevlin I see your point. But in that case you can use the year from here: https://github.com/SergioCrisostomo/js-calendar/blob/master/src/jsCalendar.js#L38-L42

	var returnObject = {
		month: month,
		year: year,
		daysInMonth: maxDays
                // cells will also be added after the for loop in the code
	};

Which could be achieved by:

    var jan2014 = jsCal(2014, 0);
    alert(jan2014.year); // 2014

does that solve the problem?

**Comment by iandevlin** [comment]
I don't think it does, as it isn't always the case. Take for example this year, the last week of December is 2015 Week 53, and the first week of January 2016 is also 2015 Week 53, so using the return object's date in this instance would also be incorrect.

**Comment by SergioCrisostomo** [comment]
@iandevlin check this: https://github.com/SergioCrisostomo/js-calendar/blob/master/src/jsCalendar.js#L73

I added a new property. It will have the year of the date in question. Basically same as `cell.date.getFullYear();`. I supose that is what you were looking for.

**Comment by iandevlin** [comment]
Well no to be honest, as its value is still incorrect, as the last week of 2014 is actualy 2015 week 1.

I will see if I can come up with something.

**Comment by SergioCrisostomo** [comment]
@iandevlin then I am not sure what you mean :dizzy_face: 

I'm happy with that adition I made yesterday, I can see use case for it anyway

**Comment by iandevlin** [comment]
I have issued a merge request, which might explain things a bit better.
