### ISSUE TITLE
Support for US format

### ISSUE THREAD

**Issue by iandevlin** [SergioCrisostomo/js-calendar#7]
The (odd) format that the US uses states that the week should start on a Sunday and not on a Monday. Are there any plans to support this in the future?

**Comment by iandevlin** [comment]
Ah wait, this.weekStart is what this is for, is it not?
1 = start on a Monday, 0 = start on a Sunday?

**Comment by iandevlin** [comment]
I am a twat, you have already built all that in. Ignore me, nothing to see here...

**Comment by SergioCrisostomo** [comment]
@iandevlin yes, that is the purpose of that `this.weekStart`. I leave this open so I can review that functionality and make specs for it. 

I will close this is that functionality is working good and with tests done.

**Comment by SergioCrisostomo** [comment]
@iandevlin welcome to double-check the fix I just merged works as it should :)

**Comment by iandevlin** [comment]
@SergioCrisostomo Hi, sadly not, there is now an error where, with the US dates, the last 14 days in a month have the same week number which breaks things.

**Comment by SergioCrisostomo** [comment]
@iandevlin can you point out what is wrong here -> http://jsfiddle.net/La7cwne8/

**Comment by iandevlin** [comment]
If you change the year to 2015 and run it, you will see that the last two weeks in December both have a week number of 1, which is incorrect.
Also, the entire week should not be included there as al of it it is part of the next month.

**Comment by iandevlin** [comment]
Also, if you look at http://jsfiddle.net/ogcwkf22/
How come the first 14 dates all have week 6?
If you change the weekStart to 1, the week numbers are correct.

**Comment by iandevlin** [comment]
I think it's back to the same issue that I fixed in my most recent pull request.
Line 101 perhaps should be:
```javascript
if (i > (weekStart - 1)) weekNr = getDateInfo(year, currentMonth, day + 1, iso);
```

**Comment by SergioCrisostomo** [comment]
@iandevlin yes, there was a regression there. Am looking at it also.
